import json
import subprocess

import pytest

import configure_capacity as configurator
from subgen_core.resource_management import GIB


def docker_result(**overrides):
    payload = {
        "OSType": "linux",
        "MemTotal": 32 * GIB,
        "MemoryLimit": True,
        "SwapLimit": True,
        "CgroupDriver": "systemd",
        "CgroupVersion": "2",
        "SecurityOptions": [],
    }
    payload.update(overrides)
    return subprocess.CompletedProcess(
        ["docker", "info"],
        0,
        stdout=json.dumps(payload),
        stderr="",
    )


def test_docker_engine_capacity_requires_linux_memory_and_swap_limits():
    assert (
        configurator.inspect_docker_engine_memory(
            lambda *args, **kwargs: docker_result()
        )
        == 32 * GIB
    )

    for override, message in (
        ({"OSType": "windows"}, "Linux Docker engine"),
        ({"MemoryLimit": False}, "memory limits"),
        ({"SwapLimit": False}, "no-extra-swap"),
        ({"MemTotal": "32"}, "total memory"),
        ({"MemTotal": 3 * GIB}, "at least 4 GiB"),
    ):
        with pytest.raises(configurator.CapacityConfigurationError, match=message):
            configurator.inspect_docker_engine_memory(
                lambda *args, _override=override, **kwargs: docker_result(**_override)
            )


def test_docker_engine_capacity_fails_closed_on_command_or_payload_error():
    def unavailable(*args, **kwargs):
        raise FileNotFoundError("docker")

    with pytest.raises(configurator.CapacityConfigurationError, match="inspected"):
        configurator.inspect_docker_engine_memory(unavailable)
    with pytest.raises(configurator.CapacityConfigurationError, match="metadata"):
        configurator.inspect_docker_engine_memory(
            lambda *args, **kwargs: subprocess.CompletedProcess(
                ["docker", "info"], 0, stdout="not-json", stderr=""
            )
        )


def test_docker_engine_rejects_unenforced_cgroups_and_unsupported_rootless_mode():
    for override, message in (
        ({"CgroupDriver": "none"}, "resource limits are unavailable"),
        (
            {"SecurityOptions": ["name=rootless"], "CgroupVersion": "1"},
            "cgroup v2 with systemd",
        ),
        (
            {"SecurityOptions": ["name=rootless"], "CgroupDriver": "cgroupfs"},
            "cgroup v2 with systemd",
        ),
    ):
        with pytest.raises(configurator.CapacityConfigurationError, match=message):
            configurator.inspect_docker_engine_capacity(
                lambda *args, _override=override, **kwargs: docker_result(**_override)
            )


@pytest.mark.parametrize(
    ("host_gib", "expected"),
    [
        (4, "3072m"),
        (6, "5120m"),
        (9, "7680m"),
        (12, "10240m"),
        (16, "13824m"),
        (24, "20736m"),
        (32, "24576m"),
        (64, "24576m"),
        (128, "24576m"),
    ],
)
def test_configurator_renders_integer_mib_hardware_matrix(host_gib, expected):
    assert configurator.render_memory_limit(host_gib * GIB) == expected


def test_guaranteed_vm_floor_must_be_stable_and_not_exceed_engine():
    floor = configurator.parse_guaranteed_memory_bytes("20")
    assert floor == 20 * GIB
    assert configurator.resolve_stable_capacity_bytes(24 * GIB, floor) == floor

    with pytest.raises(configurator.CapacityConfigurationError, match="cannot exceed"):
        configurator.resolve_stable_capacity_bytes(16 * GIB, 20 * GIB)
    for raw in ("", "nan", "-1", "3.99"):
        with pytest.raises(configurator.CapacityConfigurationError):
            configurator.parse_guaranteed_memory_bytes(raw)


def test_capacity_compose_is_literal_and_shell_environment_cannot_override_it(tmp_path):
    capacity_file = tmp_path / ".subgen-capacity.yml"

    configurator.write_capacity_compose(capacity_file, 12 * GIB)

    assert capacity_file.read_text(encoding="utf-8") == (
        "# Generated by configure_capacity.py; rerun it when hardware changes.\n"
        "services:\n"
        "  subgen-capacity:\n"
        "    mem_limit: 10240m\n"
        "    memswap_limit: 10240m\n"
        "    oom_score_adj: 1000\n"
    )


def test_secret_environment_mode_must_be_owner_only_on_posix():
    assert configurator.environment_permissions_are_private(0o600, "posix") is True
    assert configurator.environment_permissions_are_private(0o640, "posix") is False
    assert configurator.environment_permissions_are_private(0o644, "posix") is False
    assert configurator.environment_permissions_are_private(0o644, "nt") is True


def test_main_uses_verified_lower_vm_floor_and_updates_selected_env(tmp_path, capsys):
    env_file = tmp_path / "subgen.env"
    env_file.write_text("MEDIA_ROOT=/media\n", encoding="utf-8")
    env_file.chmod(0o600)
    capacity_file = tmp_path / ".subgen-capacity.yml"

    exit_code = configurator.main(
        [
            "--env-file",
            str(env_file),
            "--capacity-file",
            str(capacity_file),
            "--guaranteed-memory-gib",
            "12",
        ],
        runner=lambda *args, **kwargs: docker_result(MemTotal=24 * GIB),
    )

    assert exit_code == 0
    assert "mem_limit: 10240m" in capacity_file.read_text(encoding="utf-8")
    assert env_file.read_text(encoding="utf-8") == "MEDIA_ROOT=/media\n"
    assert "host reserve=2048 MiB" in capsys.readouterr().out


def test_rootless_engine_requires_explicit_verified_floor(tmp_path):
    env_file = tmp_path / ".env"
    env_file.write_text("MEDIA_ROOT=/media\n", encoding="utf-8")
    env_file.chmod(0o600)
    capacity_file = tmp_path / ".subgen-capacity.yml"
    def rootless(*args, **kwargs):
        return docker_result(SecurityOptions=["name=rootless"])

    assert (
        configurator.main(
            ["--env-file", str(env_file), "--capacity-file", str(capacity_file)],
            runner=rootless,
        )
        == 2
    )
    assert not capacity_file.exists()
    assert (
        configurator.main(
            [
                "--env-file",
                str(env_file),
                "--capacity-file",
                str(capacity_file),
                "--guaranteed-memory-gib",
                "12",
            ],
            runner=rootless,
        )
        == 0
    )


def test_main_does_not_write_when_capacity_cannot_be_verified(tmp_path):
    env_file = tmp_path / ".env"
    env_file.write_text("MEDIA_ROOT=/media\n", encoding="utf-8")
    env_file.chmod(0o600)
    capacity_file = tmp_path / ".subgen-capacity.yml"

    exit_code = configurator.main(
        ["--env-file", str(env_file), "--capacity-file", str(capacity_file)],
        runner=lambda *args, **kwargs: docker_result(SwapLimit=False),
    )

    assert exit_code == 2
    assert not capacity_file.exists()
